### ISSUE TITLE
V3 API Credentials Security

### ISSUE THREAD

**Issue by PeteyRev** [bigcommerce/api#115]
This is more a general question and I am sorry if it doesn't belong here - I know that you can grant permissions for API credentials - so if I were to create a set and only grant READ permissions for the product catalog, would there be any risk if these were exposed on the client front end?

**Comment by PeteyRev** [comment]
@tatiana-perry Thanks for replying - I guess my question would then be why is it a risk, if you are only allowing READ writes to that particular set of credentials - if someone were to stumble upon it its not like they could do anything malicious right? 

all our current processes ping another app which is used to authorize, I know this is considered best practice - more just a question out of curiosity

**Comment by tatiana-perry** [comment]
@PeteyRev 
Exposing credentials is a security since they can be found by malicious actors who could use them to download the entire product catalog. They might also try to use the credentials to access other parts of the store. While they are read-only, if the number of API requests increases past the plan limits you run the risk of having the credentials revoked and the app blacklisted while we investigate the issue.

**Comment by PeteyRev** [comment]
@tatiana-perry ah, fair enough. Thanks for the explanation!
