### ISSUE TITLE
Allow shipping_method to be included when creating a shipment

### ISSUE THREAD

**Issue by flyingL123** [bigcommerce/api#23]
With the v3 api, will the shipping_method field be writable when creating a shipment? With the v2 api, you can't include a shipping_method when creating a shipment. This means apps like ShipStation can not be used effectively since they will post back the tracking numbers but not the shipping method, causing confusion for customers.

Will this be updated in the v3 api so that apps like ShipStation can provide a shipping_method when creating shipments via the api?

**Comment by bc-jz** [comment]
Hi @flyingL123 ,

A somewhat recent update detailed here:

https://developer.bigcommerce.com/blog/changelog/order-shipment-provider

added two new properties which do allow Shipstation (and others) to update the actual "shipping method" on an order's shipment.  In the v2 API the "shipping_method" property on a shipment really updates a "Shipping Method Description" value on our end.  The two new properties of "shipping_provider" and "tracking_carrier" though allow you to change the actual shipping method so that tracking numbers in the shipment update emails link properly.

We could not change the functionality of the "shipping_method" property in v2 even though it is confusing as that would break current integrations.  In v3 though we can look at making the property names better describe what they affect.

In any case, Shipstation can get this going using the v2 API with some updates on their end.

Please let me know if you have questions on the above information.

**Comment by bc-jz** [comment]
I am closing this issue as the above information should resolve the problem stated by the OP.  If anyone has further questions around this feel free to comment and we can still discuss and reopen the issue as needed.
