### ISSUE TITLE
V3 Multi-Curl Reads and Writes

### ISSUE THREAD

**Issue by jlee2027** [bigcommerce/api#63]
More general questions than issues. 

Is is possible to use (php) curl_multi_init with V3 to read products?
Is is possible to use (php) curl_multi_init with V3 to write products?
How many multi instances of Curl will V3 support?
Do different store plans (Basic versus Enterprise) affect the number of instances ?

Thanks

**Comment by bc-AlyssNoland** [comment]
Request authenticated with OAuth are rate limited based on a quota that is refreshed every five seconds. The maximum quota for a store will vary depending on the store’s plan (such as basic or enterprise). Each request to the API consumes one available request from the quota. When the quota limit is reached, subsequent requests are rejected until the quota is refreshed.

I couldn't tell you offhand how many instances will be supported, but you can test for when you receive the 429 response to determine. I'd start with a lower number because it will affect your storefront performance.

**Comment by jlee2027** [comment]
Thank you. V3 has been a pleasant surprise in performance and design. I am implementing it as quickly as I can!
