### ISSUE TITLE
Resource Naming Varies Greatly From Order

### ISSUE THREAD

**Issue by carsonreinke** [bigcommerce/api#7]
Appears that the naming of the properties within the resources are far different from existing resources, such as the Order (e.g. `consignments`, `grand_total`)

**Comment by serroba** [comment]
Thanks @carsonreinke !

Let me explain a bit further this. Maybe we should pay extra attention to this in the description of the document.

* `consignments`: This is different, because this actually doesn't exists in any API endpoint we currently provide. The idea of consignment is a property that will allow us to expose required information when a shopper has chosen multiple shipping addresses. This is something we handle just internally so far, and this is the first time we would be exposing this. So that's why this is a new term.
* `grand_total`: True, we may consider to use the name of V2, if this generates problems. The name should reflect for most of the cases what we expose currently in V2 under `order.total_inc_tax`
* `balance_due`: This is another new property. We currently do not present a difference of the grand total and the remaining balance, or balance due. When a shopper has a applied/used any form of digital currency (ie. Gift Certificate) we present this as part of the total (behaving more like a form of discount rather than a payment method). So with this current approach we would like to expose this clearly.

Also, feel free to add comments to this PR https://github.com/bigcommerce/api/pull/2, which is a clone document in the form of PR, so to facilitate feedback
